"""initial_schema

Revision ID: 120a64c0ed0a
Revises: 
Create Date: 2026-04-22 03:10:12.517619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120a64c0ed0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('payment_method', sa.Enum('crypto', 'telegram_stars', name='payment_method_enum'), nullable=False),
    sa.Column('currency', sa.Enum('USDT', 'USDC', 'XRP', 'SOL', name='currency_code_enum'), nullable=True),
    sa.Column('network', sa.Enum('TRC20', 'ERC20', 'BEP20', 'POLYGON', 'SOLANA', 'XRPL', name='network_code_enum'), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_options_code'), 'payment_options', ['code'], unique=True)
    op.create_index(op.f('ix_payment_options_currency'), 'payment_options', ['currency'], unique=False)
    op.create_index(op.f('ix_payment_options_network'), 'payment_options', ['network'], unique=False)
    op.create_index(op.f('ix_payment_options_payment_method'), 'payment_options', ['payment_method'], unique=False)
    op.create_table('system_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_errors_entity_id'), 'system_errors', ['entity_id'], unique=False)
    op.create_index(op.f('ix_system_errors_entity_type'), 'system_errors', ['entity_type'], unique=False)
    op.create_index(op.f('ix_system_errors_error_type'), 'system_errors', ['error_type'], unique=False)
    op.create_index(op.f('ix_system_errors_is_resolved'), 'system_errors', ['is_resolved'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('vpn_servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('panel_url', sa.String(length=255), nullable=True),
    sa.Column('api_type', sa.String(length=32), server_default='3xui', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_load', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpn_servers_name'), 'vpn_servers', ['name'], unique=True)
    op.create_index(op.f('ix_vpn_servers_status'), 'vpn_servers', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'waiting_payment', 'paid', 'activated', 'expired', 'cancelled', 'failed', name='order_status_enum'), server_default='created', nullable=False),
    sa.Column('tariff_code', sa.Enum('devices_1', 'devices_2', 'devices_3', name='tariff_code_enum'), nullable=False),
    sa.Column('device_limit', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('crypto', 'telegram_stars', name='payment_method_enum'), nullable=False),
    sa.Column('payment_option_id', sa.Integer(), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('expected_currency', sa.Enum('USDT', 'USDC', 'XRP', 'SOL', name='currency_code_enum'), nullable=True),
    sa.Column('expected_network', sa.Enum('TRC20', 'ERC20', 'BEP20', 'POLYGON', 'SOLANA', 'XRPL', name='network_code_enum'), nullable=True),
    sa.Column('destination_address', sa.String(length=255), nullable=True),
    sa.Column('destination_memo_tag', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), server_default=sa.text("'bot'"), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_option_id'], ['payment_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_expected_currency'), 'orders', ['expected_currency'], unique=False)
    op.create_index(op.f('ix_orders_expected_network'), 'orders', ['expected_network'], unique=False)
    op.create_index(op.f('ix_orders_expires_at'), 'orders', ['expires_at'], unique=False)
    op.create_index(op.f('ix_orders_payment_method'), 'orders', ['payment_method'], unique=False)
    op.create_index(op.f('ix_orders_payment_option_id'), 'orders', ['payment_option_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_tariff_code'), 'orders', ['tariff_code'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'detected', 'confirmed', 'invalid', 'duplicate', 'expired', 'error', name='payment_status_enum'), server_default='new', nullable=False),
    sa.Column('payment_method', sa.Enum('crypto', 'telegram_stars', name='payment_method_enum'), nullable=False),
    sa.Column('payment_option_id', sa.Integer(), nullable=True),
    sa.Column('txid', sa.String(length=255), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('currency', sa.Enum('USDT', 'USDC', 'XRP', 'SOL', name='currency_code_enum'), nullable=True),
    sa.Column('network', sa.Enum('TRC20', 'ERC20', 'BEP20', 'POLYGON', 'SOLANA', 'XRPL', name='network_code_enum'), nullable=True),
    sa.Column('address_from', sa.String(length=255), nullable=True),
    sa.Column('address_to', sa.String(length=255), nullable=True),
    sa.Column('memo_tag', sa.String(length=255), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_option_id'], ['payment_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_currency'), 'payments', ['currency'], unique=False)
    op.create_index(op.f('ix_payments_network'), 'payments', ['network'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_method'), 'payments', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payments_payment_option_id'), 'payments', ['payment_option_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_txid'), 'payments', ['txid'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('vpn_server_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('inactive', 'active', 'expired', 'disabled', 'error', name='subscription_status_enum'), server_default='inactive', nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('device_limit', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_access_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=True),
    sa.Column('error_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vpn_server_id'], ['vpn_servers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_expires_at'), 'subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_order_id'), 'subscriptions', ['order_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_uuid'), 'subscriptions', ['uuid'], unique=True)
    op.create_index(op.f('ix_subscriptions_vpn_server_id'), 'subscriptions', ['vpn_server_id'], unique=False)
    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_actions_action_type'), 'admin_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_admin_actions_admin_user_id'), 'admin_actions', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_actions_order_id'), 'admin_actions', ['order_id'], unique=False)
    op.create_index(op.f('ix_admin_actions_payment_id'), 'admin_actions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_admin_actions_subscription_id'), 'admin_actions', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_admin_actions_target_user_id'), 'admin_actions', ['target_user_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('txid', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processing_status', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_event_type'), 'payment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_events_external_event_id'), 'payment_events', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_payment_events_order_id'), 'payment_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_events_processed'), 'payment_events', ['processed'], unique=False)
    op.create_index(op.f('ix_payment_events_processing_status'), 'payment_events', ['processing_status'], unique=False)
    op.create_index(op.f('ix_payment_events_provider'), 'payment_events', ['provider'], unique=False)
    op.create_index(op.f('ix_payment_events_txid'), 'payment_events', ['txid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_events_txid'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_provider'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_processing_status'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_processed'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_order_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_external_event_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_type'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_admin_actions_target_user_id'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_subscription_id'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_payment_id'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_order_id'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_admin_user_id'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_action_type'), table_name='admin_actions')
    op.drop_table('admin_actions')
    op.drop_index(op.f('ix_subscriptions_vpn_server_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_uuid'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_order_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_expires_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_txid'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_option_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_network'), table_name='payments')
    op.drop_index(op.f('ix_payments_currency'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_tariff_code'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_option_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_method'), table_name='orders')
    op.drop_index(op.f('ix_orders_expires_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_expected_network'), table_name='orders')
    op.drop_index(op.f('ix_orders_expected_currency'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_vpn_servers_status'), table_name='vpn_servers')
    op.drop_index(op.f('ix_vpn_servers_name'), table_name='vpn_servers')
    op.drop_table('vpn_servers')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_errors_is_resolved'), table_name='system_errors')
    op.drop_index(op.f('ix_system_errors_error_type'), table_name='system_errors')
    op.drop_index(op.f('ix_system_errors_entity_type'), table_name='system_errors')
    op.drop_index(op.f('ix_system_errors_entity_id'), table_name='system_errors')
    op.drop_table('system_errors')
    op.drop_index(op.f('ix_payment_options_payment_method'), table_name='payment_options')
    op.drop_index(op.f('ix_payment_options_network'), table_name='payment_options')
    op.drop_index(op.f('ix_payment_options_currency'), table_name='payment_options')
    op.drop_index(op.f('ix_payment_options_code'), table_name='payment_options')
    op.drop_table('payment_options')
    # ### end Alembic commands ###
